# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: similarity.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10similarity.proto\x12\nsimilarity\"U\n\x11similarityRequest\x12\x10\n\x08\x63hoices1\x18\x01 \x03(\x05\x12\r\n\x05text1\x18\x02 \x01(\t\x12\x10\n\x08\x63hoices2\x18\x03 \x03(\x05\x12\r\n\x05text2\x18\x04 \x01(\t\"#\n\x12similarityResponse\x12\r\n\x05score\x18\x01 \x01(\x01\x32^\n\nSimilarity\x12P\n\rgetSimilarity\x12\x1d.similarity.similarityRequest\x1a\x1e.similarity.similarityResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'similarity_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMILARITYREQUEST._serialized_start=32
  _SIMILARITYREQUEST._serialized_end=117
  _SIMILARITYRESPONSE._serialized_start=119
  _SIMILARITYRESPONSE._serialized_end=154
  _SIMILARITY._serialized_start=156
  _SIMILARITY._serialized_end=250
# @@protoc_insertion_point(module_scope)
