// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: similarity.proto

package similarity;

/**
 * Protobuf type {@code similarity.similarityRequest}
 */
public final class similarityRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:similarity.similarityRequest)
    similarityRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use similarityRequest.newBuilder() to construct.
  private similarityRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private similarityRequest() {
    choices1_ = emptyIntList();
    text1_ = "";
    choices2_ = emptyIntList();
    text2_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new similarityRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return similarity.SimilarityService.internal_static_similarity_similarityRequest_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return similarity.SimilarityService.internal_static_similarity_similarityRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            similarity.similarityRequest.class, similarity.similarityRequest.Builder.class);
  }

  public static final int CHOICES1_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.IntList choices1_;
  /**
   * <code>repeated int32 choices1 = 1;</code>
   * @return A list containing the choices1.
   */
  @Override
  public java.util.List<Integer>
      getChoices1List() {
    return choices1_;
  }
  /**
   * <code>repeated int32 choices1 = 1;</code>
   * @return The count of choices1.
   */
  public int getChoices1Count() {
    return choices1_.size();
  }
  /**
   * <code>repeated int32 choices1 = 1;</code>
   * @param index The index of the element to return.
   * @return The choices1 at the given index.
   */
  public int getChoices1(int index) {
    return choices1_.getInt(index);
  }
  private int choices1MemoizedSerializedSize = -1;

  public static final int TEXT1_FIELD_NUMBER = 2;
  private volatile Object text1_;
  /**
   * <code>string text1 = 2;</code>
   * @return The text1.
   */
  @Override
  public String getText1() {
    Object ref = text1_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      text1_ = s;
      return s;
    }
  }
  /**
   * <code>string text1 = 2;</code>
   * @return The bytes for text1.
   */
  @Override
  public com.google.protobuf.ByteString
      getText1Bytes() {
    Object ref = text1_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      text1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHOICES2_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.IntList choices2_;
  /**
   * <code>repeated int32 choices2 = 3;</code>
   * @return A list containing the choices2.
   */
  @Override
  public java.util.List<Integer>
      getChoices2List() {
    return choices2_;
  }
  /**
   * <code>repeated int32 choices2 = 3;</code>
   * @return The count of choices2.
   */
  public int getChoices2Count() {
    return choices2_.size();
  }
  /**
   * <code>repeated int32 choices2 = 3;</code>
   * @param index The index of the element to return.
   * @return The choices2 at the given index.
   */
  public int getChoices2(int index) {
    return choices2_.getInt(index);
  }
  private int choices2MemoizedSerializedSize = -1;

  public static final int TEXT2_FIELD_NUMBER = 4;
  private volatile Object text2_;
  /**
   * <code>string text2 = 4;</code>
   * @return The text2.
   */
  @Override
  public String getText2() {
    Object ref = text2_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      text2_ = s;
      return s;
    }
  }
  /**
   * <code>string text2 = 4;</code>
   * @return The bytes for text2.
   */
  @Override
  public com.google.protobuf.ByteString
      getText2Bytes() {
    Object ref = text2_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      text2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getChoices1List().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(choices1MemoizedSerializedSize);
    }
    for (int i = 0; i < choices1_.size(); i++) {
      output.writeInt32NoTag(choices1_.getInt(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text1_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, text1_);
    }
    if (getChoices2List().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(choices2MemoizedSerializedSize);
    }
    for (int i = 0; i < choices2_.size(); i++) {
      output.writeInt32NoTag(choices2_.getInt(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text2_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, text2_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < choices1_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(choices1_.getInt(i));
      }
      size += dataSize;
      if (!getChoices1List().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      choices1MemoizedSerializedSize = dataSize;
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text1_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, text1_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < choices2_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(choices2_.getInt(i));
      }
      size += dataSize;
      if (!getChoices2List().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      choices2MemoizedSerializedSize = dataSize;
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text2_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, text2_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof similarity.similarityRequest)) {
      return super.equals(obj);
    }
    similarity.similarityRequest other = (similarity.similarityRequest) obj;

    if (!getChoices1List()
        .equals(other.getChoices1List())) return false;
    if (!getText1()
        .equals(other.getText1())) return false;
    if (!getChoices2List()
        .equals(other.getChoices2List())) return false;
    if (!getText2()
        .equals(other.getText2())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getChoices1Count() > 0) {
      hash = (37 * hash) + CHOICES1_FIELD_NUMBER;
      hash = (53 * hash) + getChoices1List().hashCode();
    }
    hash = (37 * hash) + TEXT1_FIELD_NUMBER;
    hash = (53 * hash) + getText1().hashCode();
    if (getChoices2Count() > 0) {
      hash = (37 * hash) + CHOICES2_FIELD_NUMBER;
      hash = (53 * hash) + getChoices2List().hashCode();
    }
    hash = (37 * hash) + TEXT2_FIELD_NUMBER;
    hash = (53 * hash) + getText2().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static similarity.similarityRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static similarity.similarityRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static similarity.similarityRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static similarity.similarityRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static similarity.similarityRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static similarity.similarityRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static similarity.similarityRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static similarity.similarityRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static similarity.similarityRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static similarity.similarityRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static similarity.similarityRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static similarity.similarityRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(similarity.similarityRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code similarity.similarityRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:similarity.similarityRequest)
      similarity.similarityRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return similarity.SimilarityService.internal_static_similarity_similarityRequest_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return similarity.SimilarityService.internal_static_similarity_similarityRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              similarity.similarityRequest.class, similarity.similarityRequest.Builder.class);
    }

    // Construct using similarity.similarityRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      choices1_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      text1_ = "";

      choices2_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      text2_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return similarity.SimilarityService.internal_static_similarity_similarityRequest_descriptor;
    }

    @Override
    public similarity.similarityRequest getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public similarity.similarityRequest build() {
      similarity.similarityRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public similarity.similarityRequest buildPartial() {
      similarity.similarityRequest result = new similarity.similarityRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        choices1_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.choices1_ = choices1_;
      result.text1_ = text1_;
      if (((bitField0_ & 0x00000002) != 0)) {
        choices2_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.choices2_ = choices2_;
      result.text2_ = text2_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof similarity.similarityRequest) {
        return mergeFrom((similarity.similarityRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(similarity.similarityRequest other) {
      if (other == getDefaultInstance()) return this;
      if (!other.choices1_.isEmpty()) {
        if (choices1_.isEmpty()) {
          choices1_ = other.choices1_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureChoices1IsMutable();
          choices1_.addAll(other.choices1_);
        }
        onChanged();
      }
      if (!other.getText1().isEmpty()) {
        text1_ = other.text1_;
        onChanged();
      }
      if (!other.choices2_.isEmpty()) {
        if (choices2_.isEmpty()) {
          choices2_ = other.choices2_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureChoices2IsMutable();
          choices2_.addAll(other.choices2_);
        }
        onChanged();
      }
      if (!other.getText2().isEmpty()) {
        text2_ = other.text2_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int v = input.readInt32();
              ensureChoices1IsMutable();
              choices1_.addInt(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureChoices1IsMutable();
              while (input.getBytesUntilLimit() > 0) {
                choices1_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 10
            case 18: {
              text1_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 24: {
              int v = input.readInt32();
              ensureChoices2IsMutable();
              choices2_.addInt(v);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureChoices2IsMutable();
              while (input.getBytesUntilLimit() > 0) {
                choices2_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 26
            case 34: {
              text2_ = input.readStringRequireUtf8();

              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList choices1_ = emptyIntList();
    private void ensureChoices1IsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        choices1_ = mutableCopy(choices1_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 choices1 = 1;</code>
     * @return A list containing the choices1.
     */
    public java.util.List<Integer>
        getChoices1List() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(choices1_) : choices1_;
    }
    /**
     * <code>repeated int32 choices1 = 1;</code>
     * @return The count of choices1.
     */
    public int getChoices1Count() {
      return choices1_.size();
    }
    /**
     * <code>repeated int32 choices1 = 1;</code>
     * @param index The index of the element to return.
     * @return The choices1 at the given index.
     */
    public int getChoices1(int index) {
      return choices1_.getInt(index);
    }
    /**
     * <code>repeated int32 choices1 = 1;</code>
     * @param index The index to set the value at.
     * @param value The choices1 to set.
     * @return This builder for chaining.
     */
    public Builder setChoices1(
        int index, int value) {
      ensureChoices1IsMutable();
      choices1_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 choices1 = 1;</code>
     * @param value The choices1 to add.
     * @return This builder for chaining.
     */
    public Builder addChoices1(int value) {
      ensureChoices1IsMutable();
      choices1_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 choices1 = 1;</code>
     * @param values The choices1 to add.
     * @return This builder for chaining.
     */
    public Builder addAllChoices1(
        Iterable<? extends Integer> values) {
      ensureChoices1IsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, choices1_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 choices1 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChoices1() {
      choices1_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private Object text1_ = "";
    /**
     * <code>string text1 = 2;</code>
     * @return The text1.
     */
    public String getText1() {
      Object ref = text1_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        text1_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string text1 = 2;</code>
     * @return The bytes for text1.
     */
    public com.google.protobuf.ByteString
        getText1Bytes() {
      Object ref = text1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        text1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string text1 = 2;</code>
     * @param value The text1 to set.
     * @return This builder for chaining.
     */
    public Builder setText1(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      text1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string text1 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearText1() {

      text1_ = getDefaultInstance().getText1();
      onChanged();
      return this;
    }
    /**
     * <code>string text1 = 2;</code>
     * @param value The bytes for text1 to set.
     * @return This builder for chaining.
     */
    public Builder setText1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      text1_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList choices2_ = emptyIntList();
    private void ensureChoices2IsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        choices2_ = mutableCopy(choices2_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated int32 choices2 = 3;</code>
     * @return A list containing the choices2.
     */
    public java.util.List<Integer>
        getChoices2List() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(choices2_) : choices2_;
    }
    /**
     * <code>repeated int32 choices2 = 3;</code>
     * @return The count of choices2.
     */
    public int getChoices2Count() {
      return choices2_.size();
    }
    /**
     * <code>repeated int32 choices2 = 3;</code>
     * @param index The index of the element to return.
     * @return The choices2 at the given index.
     */
    public int getChoices2(int index) {
      return choices2_.getInt(index);
    }
    /**
     * <code>repeated int32 choices2 = 3;</code>
     * @param index The index to set the value at.
     * @param value The choices2 to set.
     * @return This builder for chaining.
     */
    public Builder setChoices2(
        int index, int value) {
      ensureChoices2IsMutable();
      choices2_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 choices2 = 3;</code>
     * @param value The choices2 to add.
     * @return This builder for chaining.
     */
    public Builder addChoices2(int value) {
      ensureChoices2IsMutable();
      choices2_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 choices2 = 3;</code>
     * @param values The choices2 to add.
     * @return This builder for chaining.
     */
    public Builder addAllChoices2(
        Iterable<? extends Integer> values) {
      ensureChoices2IsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, choices2_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 choices2 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearChoices2() {
      choices2_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private Object text2_ = "";
    /**
     * <code>string text2 = 4;</code>
     * @return The text2.
     */
    public String getText2() {
      Object ref = text2_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        text2_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string text2 = 4;</code>
     * @return The bytes for text2.
     */
    public com.google.protobuf.ByteString
        getText2Bytes() {
      Object ref = text2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        text2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string text2 = 4;</code>
     * @param value The text2 to set.
     * @return This builder for chaining.
     */
    public Builder setText2(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      text2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string text2 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearText2() {

      text2_ = getDefaultInstance().getText2();
      onChanged();
      return this;
    }
    /**
     * <code>string text2 = 4;</code>
     * @param value The bytes for text2 to set.
     * @return This builder for chaining.
     */
    public Builder setText2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      text2_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:similarity.similarityRequest)
  }

  // @@protoc_insertion_point(class_scope:similarity.similarityRequest)
  private static final similarity.similarityRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new similarity.similarityRequest();
  }

  public static similarity.similarityRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<similarityRequest>
      PARSER = new com.google.protobuf.AbstractParser<similarityRequest>() {
    @Override
    public similarityRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<similarityRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<similarityRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public similarity.similarityRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

