// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: similarity.proto

package similarity;

public interface similarityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:similarity.similarityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double score = 1;</code>
   * @return The score.
   */
  double getScore();
}
