// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: similarity.proto

package similarity;

public interface similarityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:similarity.similarityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 choices1 = 1;</code>
   * @return A list containing the choices1.
   */
  java.util.List<Integer> getChoices1List();
  /**
   * <code>repeated int32 choices1 = 1;</code>
   * @return The count of choices1.
   */
  int getChoices1Count();
  /**
   * <code>repeated int32 choices1 = 1;</code>
   * @param index The index of the element to return.
   * @return The choices1 at the given index.
   */
  int getChoices1(int index);

  /**
   * <code>string text1 = 2;</code>
   * @return The text1.
   */
  String getText1();
  /**
   * <code>string text1 = 2;</code>
   * @return The bytes for text1.
   */
  com.google.protobuf.ByteString
      getText1Bytes();

  /**
   * <code>repeated int32 choices2 = 3;</code>
   * @return A list containing the choices2.
   */
  java.util.List<Integer> getChoices2List();
  /**
   * <code>repeated int32 choices2 = 3;</code>
   * @return The count of choices2.
   */
  int getChoices2Count();
  /**
   * <code>repeated int32 choices2 = 3;</code>
   * @param index The index of the element to return.
   * @return The choices2 at the given index.
   */
  int getChoices2(int index);

  /**
   * <code>string text2 = 4;</code>
   * @return The text2.
   */
  String getText2();
  /**
   * <code>string text2 = 4;</code>
   * @return The bytes for text2.
   */
  com.google.protobuf.ByteString
      getText2Bytes();
}
